site_name: Abelaa Documentation
site_url: https://flutter.dev/docs

nav:
  - Home: index.md
  - About: about.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Guides:
      - Configuration: guides/configuration.md
      - Theming: guides/theming.md
      - Plugins: guides/plugins.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Francais
      link: /docs/fr/
      lang: fr

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - search.suggestions
    - search.highlight
    - toc.integrated
    - header.autohide
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
copyright: 
  Copyright &copy; 2024 abelaa. Tous droits réservés. Fait ❤️ avec pour la communauté