site_name: Abelaa Documentation
site_url: https://flutter.dev/docs

nav:
  - Home: index.md
  - About: about.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Get Abelaa: getting-started/get.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Guides:
      - Inventary: guides/inventaire.md
      - Marketplace: guides/marketplace.md
      - Potential: guides/potential.md
      - Dashboard: guides/dashboard.md
      - Theming: guides/theming.md
      
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Francais
      link: /docs/fr/
      lang: fr

plugins:
  - search # Default search plugin
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: Abelaa Documentation
        - locale: fr
          name: Francais
          build: true
          site_name: Documentation Abelaa
          nav:
            - Accueil: index.fr.md
            - A propos: about.fr.md
            - Demarrage:
                - Introduction: getting-started/introduction.fr.md
                - Obtenir Abelaa: getting-started/get.fr.md
                - Installation: getting-started/installation.fr.md
                - Démarrage rapide: getting-started/quick-start.fr.md
            - Guides:
                - Inventaire: guides/inventaire.fr.md
                - Marché: guides/marketplace.fr.md
                - Potentiel: guides/potential.fr.md
                - Tableau de bord: guides/dashboard.fr.md
                - Thème: guides/theming.fr.md
            - FAQ: faq.fr.md
  
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - search.suggestions
    - search.highlight
    - toc.integrated
    - header.autohide
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: green 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

copyright: 
  Copyright &copy; 2024 abelaa. Tous droits réservés. Fait avec ❤️ pour la communauté